/* Superquine: an incredibly recursive for-loop: Written by Alex Corkwell, 2015 */
#include <stdio.h>
#include <stdlib.h>
#include <libgen.h>
#include <unistd.h>
int main(int argc, char **argv) {
	char *s1 = "/* Superquine: an incredibly recursive for-loop: Written by Alex Corkwell, 2015 */%c#include <stdio.h>%c#include <stdlib.h>%c#include <libgen.h>%c#include <unistd.h>%cint main(int argc, char **argv) {%c";
	char *s2 = "%cchar *s%c = %c%s%c;%c%cchar *s%c = %c%s%c;%c";
	char *s3 = "%cchar t = '%ct', n = '%cn', q = '%c', b = '%c%c', p = '%c';%c";
	char *sf = "fprintf(next, ";
	char *sb = "%cFILE *next;%c%cchar comp[100], cname[100], execname[100];%c%cint num = atoi(basename(argv[0]));%c%cprintf(%c%cd%cn%c, num);%c%cnum++;%c";
	char *si = "%cif (num < 10000) {%c%c%csprintf(comp, %cgcc -o %cd %cd.c%c, num, num);%c%c%csprintf(cname, %c%cd.c%c, num);%c";
	char *sn = "%c%csprintf(execname, %c./%cd%c, num);%c%c%cnext = fopen(cname, %cw%c);%c";
	char *se = "%c%cfclose(next);%c%c%csystem(comp);%c";
	char *sr = "%c%cexecl(execname, execname, (char *) NULL);%c%c}%c%creturn 0;%c}%c";
	char *s4 = "%c%c%ss1, n, n, n, n, n, n);%c";
	char *s5 = "%c%c%ss2, t, '1', q, s1, q, n, t, '2', q, s2, q, n);%c%c%c%ss2, t, '3', q, s3, q, n, t, 'f', q, sf, q, n);%c";
	char *s6 = "%c%c%ss2, t, 'b', q, sb, q, n, t, 'i', q, si, q, n);%c%c%c%ss2, t, 'n', q, sn, q, n, t, 'e', q, se, q, n);%c";
	char *s7 = "%c%c%ss2, t, 'r', q, sr, q, n, t, '4', q, s4, q, n);%c%c%c%ss2, t, '5', q, s5, q, n, t, '6', q, s6, q, n);%c";
	char *sl = "%c%c%sse, t, t, n, t, t, n);%c%c%c%ssr, t, t, n, t, n, t, n, n);%c";
	char *sg = "%c%c%ssg, t, t, sf, n, t, t, sf, n);%c%c%c%ssl, t, t, sf, n, t, t, sf, n);%c";
	char *sh = "%c%c%sss, t, t, sf, n, t, t, sf, n);%c%c%c%ssh, t, t, sf, n, t, t, sf, n);%c";
	char *s8 = "%c%c%ss2, t, '7', q, s7, q, n, t, 'l', q, sl, q, n);%c%c%c%ss2, t, 'g', q, sg, q, n, t, 'h', q, sh, q, n);%c";
	char *sz = "%c%c%ssa, t, t, sf, n, t, t, sf, n);%c%c%c%ss9, t, t, sf, n, t, t, sf, n);%c";
	char *sy = "%c%c%ssw, t, t, sf, n, t, t, sf, n);%c%c%c%ssd, t, t, sf, n, t, t, sf, n);%c";
	char *sx = "%c%c%ss8, t, t, sf, n, t, t, sf, n);%c%c%c%sso, t, t, sf, n, t, t, sf, n);%c";
	char *so = "%c%c%ss2, t, '8', q, s8, q, n, t, 'z', q, sz, q, n);%c%c%c%ss2, t, 'y', q, sy, q, n, t, 'x', q, sx, q, n);%c";
	char *sv = "%c%c%ss6, t, t, sf, n, t, t, sf, n);%c%c%c%ss7, t, t, sf, n, t, t, sf, n);%c";
	char *sq = "%c%c%ss4, t, t, sf, n);%c%c%c%ss5, t, t, sf, n, t, t, sf, n);%c";
	char *sp = "%c%c%ssi, t, n, t, t, q, p, p, q, n, t, t, q, p, q, n);%c%c%c%ssn, t, t, q, p, q, n, t, t, q, q, n);%c";
	char *sw = "%c%c%ss2, t, 'o', q, so, q, n, t, 'v', q, sv, q, n);%c%c%c%ss2, t, 'q', q, sq, q, n, t, 'p', q, sp, q, n);%c";
	char *sc = "%c%c%ssx, t, t, sf, n, t, t, sf, n);%c%c%c%ssy, t, t, sf, n, t, t, sf, n);%c";
	char *sd = "%c%c%ss2, t, 'w', q, sw, q, n, t, 'c', q, sc, q, n);%c%c%c%ss2, t, 'd', q, sd, q, n, t, 'a', q, sa, q, n);%c";
	char *sa = "%c%c%ssu, t, t, sf, n, t, t, sf, n);%c%c%c%ssk, t, t, sf, n, t, t, sf, n);%c";
	char *sj = "%c%c%ssm, t, t, sf, n, t, t, sf, n);%c%c%c%ssc, t, t, sf, n, t, t, sf, n);%c";
	char *sk = "%c%c%ss2, t, 't', q, st, q, n, t, 'u', q, su, q, n);%c%c%c%ss2, t, '0', q, s0, q, n, t, '9', q, s9, q, n);%c";
	char *sm = "%c%c%ssq, t, t, sf, n, t, t, sf, n);%c%c%c%ssv, t, t, sf, n, t, t, sf, n);%c";
	char *ss = "%c%c%ssz, t, t, sf, n, t, t, sf, n);%c%c%c%ssj, t, t, sf, n, t, t, sf, n);%c";
	char *st = "%c%c%ss2, t, 'm', q, sm, q, n, t, 's', q, ss, q, n);%c%c%c%ss2, t, 't', q, st, q, n, t, 'u', q, su, q, n);%c";
	char *su = "%c%c%ss2, t, 'j', q, sj, q, n, t, 'k', q, sk, q, n);%c%c%c%ss2, t, 'm', q, sm, q, n, t, 's', q, ss, q, n);%c";
	char *s0 = "%c%c%ss3, t, b, b, q, b, b, p, n);%c%c%c%ssb, t, n, t, n, t, n, t, q, p, b, q, n, t, n);%c";
	char *s9 = "%c%c%ss0, t, t, sf, n, t, t, sf, n);%c%c%c%ssp, t, t, sf, n, t, t, sf, n);%c";
	char t = '\t', n = '\n', q = '"', b = '\\', p = '%';
	FILE *next;
	char comp[100], cname[100], execname[100];
	int num = atoi(basename(argv[0]));
	printf("%d\n", num);
	num++;
	if (num < 10000) {
		sprintf(comp, "gcc -o %d %d.c", num, num);
		sprintf(cname, "%d.c", num);
		sprintf(execname, "./%d", num);
		next = fopen(cname, "w");
		fprintf(next, s1, n, n, n, n, n, n);
		fprintf(next, s2, t, '1', q, s1, q, n, t, '2', q, s2, q, n);
		fprintf(next, s2, t, '3', q, s3, q, n, t, 'f', q, sf, q, n);
		fprintf(next, s2, t, 'b', q, sb, q, n, t, 'i', q, si, q, n);
		fprintf(next, s2, t, 'n', q, sn, q, n, t, 'e', q, se, q, n);
		fprintf(next, s2, t, 'r', q, sr, q, n, t, '4', q, s4, q, n);
		fprintf(next, s2, t, '5', q, s5, q, n, t, '6', q, s6, q, n);
		fprintf(next, s2, t, '7', q, s7, q, n, t, 'l', q, sl, q, n);
		fprintf(next, s2, t, 'g', q, sg, q, n, t, 'h', q, sh, q, n);
		fprintf(next, s2, t, '8', q, s8, q, n, t, 'z', q, sz, q, n);
		fprintf(next, s2, t, 'y', q, sy, q, n, t, 'x', q, sx, q, n);
		fprintf(next, s2, t, 'o', q, so, q, n, t, 'v', q, sv, q, n);
		fprintf(next, s2, t, 'q', q, sq, q, n, t, 'p', q, sp, q, n);
		fprintf(next, s2, t, 'w', q, sw, q, n, t, 'c', q, sc, q, n);
		fprintf(next, s2, t, 'd', q, sd, q, n, t, 'a', q, sa, q, n);
		fprintf(next, s2, t, 'j', q, sj, q, n, t, 'k', q, sk, q, n);
		fprintf(next, s2, t, 'm', q, sm, q, n, t, 's', q, ss, q, n);
		fprintf(next, s2, t, 't', q, st, q, n, t, 'u', q, su, q, n);
		fprintf(next, s2, t, '0', q, s0, q, n, t, '9', q, s9, q, n);
		fprintf(next, s3, t, b, b, q, b, b, p, n);
		fprintf(next, sb, t, n, t, n, t, n, t, q, p, b, q, n, t, n);
		fprintf(next, si, t, n, t, t, q, p, p, q, n, t, t, q, p, q, n);
		fprintf(next, sn, t, t, q, p, q, n, t, t, q, q, n);
		fprintf(next, s4, t, t, sf, n);
		fprintf(next, s5, t, t, sf, n, t, t, sf, n);
		fprintf(next, s6, t, t, sf, n, t, t, sf, n);
		fprintf(next, s7, t, t, sf, n, t, t, sf, n);
		fprintf(next, s8, t, t, sf, n, t, t, sf, n);
		fprintf(next, so, t, t, sf, n, t, t, sf, n);
		fprintf(next, sw, t, t, sf, n, t, t, sf, n);
		fprintf(next, sd, t, t, sf, n, t, t, sf, n);
		fprintf(next, su, t, t, sf, n, t, t, sf, n);
		fprintf(next, sk, t, t, sf, n, t, t, sf, n);
		fprintf(next, s0, t, t, sf, n, t, t, sf, n);
		fprintf(next, sp, t, t, sf, n, t, t, sf, n);
		fprintf(next, sq, t, t, sf, n, t, t, sf, n);
		fprintf(next, sv, t, t, sf, n, t, t, sf, n);
		fprintf(next, sx, t, t, sf, n, t, t, sf, n);
		fprintf(next, sy, t, t, sf, n, t, t, sf, n);
		fprintf(next, sa, t, t, sf, n, t, t, sf, n);
		fprintf(next, s9, t, t, sf, n, t, t, sf, n);
		fprintf(next, sm, t, t, sf, n, t, t, sf, n);
		fprintf(next, sc, t, t, sf, n, t, t, sf, n);
		fprintf(next, sz, t, t, sf, n, t, t, sf, n);
		fprintf(next, sj, t, t, sf, n, t, t, sf, n);
		fprintf(next, ss, t, t, sf, n, t, t, sf, n);
		fprintf(next, sh, t, t, sf, n, t, t, sf, n);
		fprintf(next, sg, t, t, sf, n, t, t, sf, n);
		fprintf(next, sl, t, t, sf, n, t, t, sf, n);
		fprintf(next, se, t, t, n, t, t, n);
		fprintf(next, sr, t, t, n, t, n, t, n, n);
		fclose(next);
		system(comp);
		execl(execname, execname, (char *) NULL);
	}
	return 0;
}
